In [33]:
from modules import io_ops
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

In [36]:
CONNSTR = f'mysql+pymysql://casaos:casaos@192.168.0.101:3306/casaos'

engine = create_engine(CONNSTR)

In [10]:
#with engine.connect() as conn:
    conn.execute("ALTER TABLE personal_finance_data ALTER COLUMN \"TIME\" TYPE DATE USING \"TIME\"::date")

In [41]:
data = pd.read_csv("export_24_08_23_959.csv",delimiter=",")
data

,TIME,TYPE,AMOUNT,CATEGORY,ACCOUNT,NOTES
0,"Dec 21, 2022 1:49 PM",(+) Income,2581000.0,House Income,Daily Driver,gaji dari papah
1,"Dec 21, 2022 1:50 PM",(+) Income,500000.0,Gift,Daily Driver,uang beli pc dari papah
2,"Dec 21, 2022 1:52 PM",(+) Income,264000.0,Reimbursements,Daily Driver,tabungan jajan
3,"Dec 21, 2022 1:55 PM",(-) Expense,824000.0,Electronics,Daily Driver,minipc + ssd 120gb + mounting brackets and cab...
4,"Dec 21, 2022 1:56 PM",(-) Expense,700000.0,Savings,Daily Driver,dana darurat
...,...,...,...,...,...,...
518,"Aug 22, 2023 8:51 PM",(-) Expense,302500.0,Social,Daily Driver,dp foto wira
519,"Aug 24, 2023 8:51 PM",(+) Income,400000.0,Gift,Daily Driver,buat foto jonas
520,"Aug 24, 2023 8:53 PM",(-) Expense,375000.0,Social,Daily Driver,jonas
521,"Aug 24, 2023 8:53 PM",(-) Expense,41000.0,Transportation,Daily Driver,gojek pita
522,"Aug 24, 2023 9:57 PM",(-) Expense,1580000.0,Trully unaccounted,Fun Funds,nggakeitung euy

In [42]:
for i, row in data.iterrows():   
    data.loc[i,"TIME"] = data.loc[i,"TIME"].rsplit(" ",2)[0]
    data.loc[i,"TIME"] = datetime.strptime(data.loc[i,"TIME"],"%b %d, %Y")
    data.loc[i,"TIME"] = datetime.strftime(data.loc[i,"TIME"],"%Y-%m-%d")

In [45]:
data.columns = data.columns.str.strip()

In [46]:
data.to_sql("personal_finance_data",engine,if_exists='fail',index=False)

523

In [2]:
new_record = ['2023-08-28', 'Expense', 'Food', '9999', 'test']

In [2]:
columns = ["TIME", "TYPE", "CATEGORY", "AMOUNT", "NOTES"]

In [25]:
df = io_ops.read_sql(columns)

In [27]:
df

[[datetime.date(2022, 12, 21),
  '(+) Income',
  'House Income',
  2581000.0,
  'gaji dari papah\n '],
 [datetime.date(2022, 12, 21),
  '(+) Income',
  'Gift',
  500000.0,
  'uang beli pc dari papah '],
 [datetime.date(2022, 12, 21),
  '(+) Income',
  'Reimbursements',
  264000.0,
  'tabungan jajan '],
 [datetime.date(2022, 12, 21),
  '(-) Expense',
  'Electronics',
  824000.0,
  'minipc + ssd 120gb + mounting brackets and cables '],
 [datetime.date(2022, 12, 21),
  '(-) Expense',
  'Savings',
  700000.0,
  'dana darurat '],
 [datetime.date(2022, 12, 21), '(-) Expense', 'Admin fee', 4000.0, 'admin '],
 [datetime.date(2022, 12, 21), '(-) Expense', 'Food', 50000.0, 'dana warkop '],
 [datetime.date(2022, 12, 22), '(-) Expense', 'Gas', 25000.0, 'shell '],
 [datetime.date(2022, 12, 22),
  '(+) Income',
  'Reimbursements',
  259000.0,
  'uang dari dana jajan sama sisa saldo pluang '],
 [datetime.date(2022, 12, 22),
  '(-) Expense',
  'Electronics',
  262400.0,
  'beli hdd '],
 [datetime.date(2022, 12, 22),
  '(*) Transfer',
  '  -  ',
  700000.0,
  'fun funds desember-januari\n '],
 [datetime.date(2022, 12, 22),
  '(+) Income',
  'Reimbursements',
  125000.0,
  'uang jajan '],
 [datetime.date(2022, 12, 22),
  '(-) Expense',
  'Electronics',
  137000.0,
  'processor dan ram '],
 [datetime.date(2022, 12, 23),
  '(-) Expense',
  'Electronics',
  34000.0,
  'beli domain '],
 [datetime.date(2022, 12, 24),
  '(-) Expense',
  'Electronics',
  26000.0,
  'beli kabel '],
 [datetime.date(2022, 12, 24),
  '(-) Expense',
  'Food',
  23000.0,
  'ayam bang dava '],
 [datetime.date(2022, 12, 24), '(-) Expense', 'Food', 28000.0, 'wagrgot '],
 [datetime.date(2022, 12, 25), '(-) Expense', 'Food', 15000.0, 'wargot\n '],
 [datetime.date(2022, 12, 25),
  '(-) Expense',
  'Food',
  143000.0,
  'Haloka makan minum '],
 [datetime.date(2022, 12, 25), '(-) Expense', 'Food', 83000.0, 'kubal dago '],
 [datetime.date(2022, 12, 25),
  '(+) Income',
  'Reimbursements',
  35000.0,
  'kubal kansa '],
 [datetime.date(2022, 12, 25),
  '(-) Expense',
  'Food',
  100000.0,
  'starbaks gres '],
 [datetime.date(2022, 12, 25),
  '(*) Transfer',
  '  -  ',
  143000.0,
  'haloka bdg '],
 [datetime.date(2022, 12, 26), '(-) Expense', 'Food', 20000.0, 'wargot '],
 [datetime.date(2022, 12, 26), '(-) Expense', 'Food', 14000.0, 'wargot '],
 [datetime.date(2022, 12, 26), '(-) Expense', 'Food', 15000.0, 'wargot '],
 [datetime.date(2022, 12, 26), '(-) Expense', 'Food', 19000.0, 'wargoy '],
 [datetime.date(2022, 12, 26), '(*) Transfer', '  -  ', 20000.0, ' '],
 [datetime.date(2022, 12, 26), '(-) Expense', 'Food', 8000.0, 'es kelapa '],
 [datetime.date(2022, 12, 26), '(-) Expense', 'Food', 8000.0, 'eskelapa '],
 [datetime.date(2022, 12, 27), '(*) Transfer', '  -  ', 150000.0, ' '],
 [datetime.date(2022, 12, 27),
  '(-) Expense',
  'Utilities',
  75000.0,
  'listrik '],
 [datetime.date(2022, 12, 27),
  '(+) Income',
  'Reimbursements',
  461000.0,
  'binance '],
 [datetime.date(2022, 12, 27), '(-) Expense', 'Food', 36000.0, 'wargot '],
 [datetime.date(2022, 12, 27),
  '(*) Transfer',
  '  -  ',
  300000.0,
  'ganti dandar '],
 [datetime.date(2022, 12, 27),
  '(-) Expense',
  'Utilities',
  48000.0,
  'laundry '],
 [datetime.date(2022, 12, 27),
  '(-) Expense',
  'Engredients Shopping',
  36000.0,
  'kecap, saori 2 '],
 [datetime.date(2022, 12, 27),
  '(-) Expense',
  'Electronics',
  38000.0,
  'beli mymoney pro '],
 [datetime.date(2022, 12, 27),
  '(-) Expense',
  'Engredients Shopping',
  20000.0,
  'air '],
 [datetime.date(2022, 12, 28), '(-) Expense', 'Food', 41000.0, 'shopeepay '],
 [datetime.date(2022, 12, 28), '(-) Expense', 'Food', 26000.0, 'dana wargot '],
 [datetime.date(2022, 12, 28),
  '(-) Expense',
  'Utilities',
  15000.0,
  'laundry '],
 [datetime.date(2022, 12, 28),
  '(+) Income',
  'House Income',
  800000.0,
  'uang pita '],
 [datetime.date(2022, 12, 29),
  '(+) Income',
  'Professional Income',
  586000.0,
  'Upwork '],
 [datetime.date(2022, 12, 29), '(-) Expense', 'Food', 36000.0, 'shopeefood '],
 [datetime.date(2022, 12, 29), '(-) Expense', 'Food', 25000.0, 'wargot '],
 [datetime.date(2022, 12, 29),
  '(-) Expense',
  'Savings',
  295000.0,
  'dana darurat '],
 [datetime.date(2022, 12, 30),
  '(-) Expense',
  'Food',
  14000.0,
  'pak arie nitip darso '],
 [datetime.date(2022, 12, 30),
  '(+) Income',
  'Reimbursements',
  14000.0,
  'pak arie nitip darso '],
 [datetime.date(2022, 12, 30),
  '(-) Expense',
  'Food',
  50000.0,
  'point coffee '],
 [datetime.date(2022, 12, 31),
  '(-) Expense',
  'Medicine',
  25100.0,
  'chinstrap '],
 [datetime.date(2023, 1, 1),
  '(-) Expense',
  'Savings',
  400000.0,
  'dana darurat '],
 [datetime.date(2023, 1, 1),
  '(-) Expense',
  'Medicine',
  25000.0,
  'chinstrap tokped '],
 [datetime.date(2023, 1, 4),
  '(-) Expense',
  'Home Purchases',
  196000.0,
  'parfum ruangan, porstex, tisu, pengering ruangan dsb '],
 [datetime.date(2023, 1, 4),
  '(-) Expense',
  'Engredients Shopping',
  200000.0,
  'bahan makanan '],
 [datetime.date(2023, 1, 4), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 1, 4),
  '(-) Expense',
  'Medicine',
  30000.0,
  'micelar water '],
 [datetime.date(2023, 1, 4), '(-) Expense', 'cash out', 105000.0, 'cash '],
 [datetime.date(2023, 1, 7), '(-) Expense', 'Food', 31000.0, 'makan '],
 [datetime.date(2023, 1, 10),
  '(-) Expense',
  'Gas',
  50000.0,
  'shell trs bubat '],
 [datetime.date(2023, 1, 10), '(-) Expense', 'Food', 16000.0, 'mixue '],
 [datetime.date(2023, 1, 10),
  '(-) Expense',
  'Electronics',
  20000.0,
  'subscription minimalist phone '],
 [datetime.date(2023, 1, 10), '(-) Expense', 'Food', 23000.0, 'wargot '],
 [datetime.date(2023, 1, 12),
  '(-) Expense',
  'Engredients Shopping',
  271000.0,
  ' '],
 [datetime.date(2023, 1, 12), '(-) Expense', 'Food', 54000.0, 'ws hotplate '],
 [datetime.date(2023, 1, 16), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 1, 16), '(-) Expense', 'Food', 96500.0, 'ramen '],
 [datetime.date(2023, 1, 16),
  '(-) Expense',
  'Beauty',
  65000.0,
  'collars potong rambut '],
 [datetime.date(2023, 1, 16),
  '(+) Income',
  'Reimbursements',
  30000.0,
  'diganti khansa buat ramen '],
 [datetime.date(2023, 1, 16), '(-) Expense', 'Food', 42000.0, 'warkop dana '],
 [datetime.date(2023, 1, 16),
  '(*) Transfer',
  '  -  ',
  130000.0,
  'buat survive sampe akhir bulan '],
 [datetime.date(2023, 1, 22), '(-) Expense', 'cash out', 273000.0, ' '],
 [datetime.date(2023, 1, 22), '(-) Expense', 'Food', 194000.0, ' '],
 [datetime.date(2023, 1, 25),
  '(+) Income',
  'House Income',
  2500000.0,
  'gaji dari pops '],
 [datetime.date(2023, 1, 25),
  '(+) Income',
  'Gift',
  1500000.0,
  'hadiah ultah dari pops '],
 [datetime.date(2023, 1, 25),
  '(*) Transfer',
  '  -  ',
  1000000.0,
  'fun funds '],
 [datetime.date(2023, 1, 25),
  '(*) Transfer',
  '  -  ',
  500000.0,
  'dana darurat '],
 [datetime.date(2023, 1, 25),
  '(-) Expense',
  'Gift',
  52500.0,
  'gift for pita '],
 [datetime.date(2023, 1, 25),
  '(-) Expense',
  'Engredients Shopping',
  232197.0,
  'beras, minyak, susu ultra, sereal, kewpie, indomie goreng, jeruk nipis, roti gandum, sawi, kornet, soda kue, daun bawang '],
 [datetime.date(2023, 1, 25),
  '(-) Expense',
  'Home Purchases',
  173166.0,
  'shampoo, serap air, sabut polytex, colokan listrik, bayclin, pewangi ruangan, rinso, masker, cotton bud '],
 [datetime.date(2023, 1, 25),
  '(-) Expense',
  'Utilities',
  31000.0,
  'uang kebersihan kosan '],
 [datetime.date(2023, 1, 25),
  '(-) Expense',
  'Utilities',
  125000.0,
  'electricity '],
 [datetime.date(2023, 1, 25),
  '(-) Expense',
  'Savings',
  500000.0,
  'dana darurat '],
 [datetime.date(2023, 1, 26),
  '(+) Income',
  'Professional Income',
  1494000.0,
  'momomedia '],
 [datetime.date(2023, 1, 26),
  '(-) Expense',
  'Gift',
  250000.0,
  'hadiah buat mbazie '],
 [datetime.date(2023, 1, 26), '(-) Expense', 'Gift', 500000.0, 'kado pita '],
 [datetime.date(2023, 1, 26), '(-) Expense', 'Savings', 500000.0, 'snp 500 '],
 [datetime.date(2023, 1, 29),
  '(+) Income',
  'House Income',
  1000000.0,
  'uang bulanan pita '],
 [datetime.date(2023, 1, 29), '(-) Expense', 'Food', 66000.0, 'shopee food '],
 [datetime.date(2023, 1, 30),
  '(-) Expense',
  'Home Purchases',
  56000.0,
  'jajan peralatan rumah di shopee '],
 [datetime.date(2023, 1, 30), '(-) Expense', 'Food', 16000.0, 'warkop '],
 [datetime.date(2023, 1, 31), '(-) Expense', 'Food', 101500.0, 'sejiwa '],
 [datetime.date(2023, 1, 31), '(-) Expense', 'cash out', 106500.0, 'cash '],
 [datetime.date(2023, 2, 1), '(-) Expense', 'Food', 50000.0, 'warkop '],
 [datetime.date(2023, 2, 1), '(-) Expense', 'Gas', 30000.0, 'shell super '],
 [datetime.date(2023, 2, 2),
  '(-) Expense',
  'Electronics',
  605000.0,
  'case enlight slim '],
 [datetime.date(2023, 2, 2), '(-) Expense', 'Electronics', 1615000.0, ' '],
 [datetime.date(2023, 2, 2), '(-) Expense', 'Food', 20000.0, 'wargot '],
 [datetime.date(2023, 2, 2), '(-) Expense', 'cash out', 107500.0, 'cash '],
 [datetime.date(2023, 2, 2), '(-) Expense', 'Food', 66000.0, 'shopeepay '],
 [datetime.date(2023, 2, 2), '(-) Expense', 'Food', 26000.0, 'warkop '],
 [datetime.date(2023, 2, 6),
  '(-) Expense',
  'Engredients Shopping',
  200000.0,
  ' '],
 [datetime.date(2023, 2, 6),
  '(-) Expense',
  'Home Purchases',
  46000.0,
  'terminal '],
 [datetime.date(2023, 2, 6), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 2, 11),
  '(-) Expense',
  'Engredients Shopping',
  172500.0,
  'yogya bj '],
 [datetime.date(2023, 2, 12), '(-) Expense', 'Utilities', 67500.0, 'Laundry '],
 [datetime.date(2023, 2, 12), '(-) Expense', 'cash out', 32500.0, 'cash '],
 [datetime.date(2023, 2, 14), '(+) Income', 'Gift', 250000.0, 'papah '],
 [datetime.date(2023, 2, 14), '(-) Expense', 'Gas', 50000.0, 'shell vpower '],
 [datetime.date(2023, 2, 14),
  '(-) Expense',
  'Transportation',
  20000.0,
  'gocar '],
 [datetime.date(2023, 2, 14),
  '(-) Expense',
  'Utilities',
  50000.0,
  'uang kebersihan diora '],
 [datetime.date(2023, 2, 14), '(-) Expense', 'Admin fee', 11000.0, 'admin '],
 [datetime.date(2023, 2, 15),
  '(+) Income',
  'Gift',
  120000.0,
  'uang bayi pita '],
 [datetime.date(2023, 2, 15),
  '(-) Expense',
  'Transportation',
  20000.0,
  'grab '],
 [datetime.date(2023, 2, 16), '(-) Expense', 'Food', 62500.0, 'seafood '],
 [datetime.date(2023, 2, 16),
  '(-) Expense',
  'Gift',
  250000.0,
  'uang hidup pita '],
 [datetime.date(2023, 2, 16), '(-) Expense', 'Admin fee', 2500.0, 'trf banj '],
 [datetime.date(2023, 2, 20),
  '(-) Expense',
  'Transportation',
  50000.0,
  'gopay '],
 [datetime.date(2023, 2, 20), '(-) Expense', 'Admin fee', 15000.0, 'admin '],
 [datetime.date(2023, 2, 20),
  '(+) Income',
  'Gift',
  176000.0,
  'gift from pops '],
 [datetime.date(2023, 2, 27), '(-) Expense', 'cash out', 294673.0, ' '],
 [datetime.date(2023, 2, 27), '(-) Expense', 'cash out', 366500.0, ' '],
 [datetime.date(2023, 2, 27), '(-) Expense', 'cash out', 45000.0, ' '],
 [datetime.date(2023, 2, 27),
  '(+) Income',
  'House Income',
  1050000.0,
  'pops '],
 [datetime.date(2023, 2, 27),
  '(+) Income',
  'House Income',
  1000000.0,
  'pops '],
 [datetime.date(2023, 2, 27), '(+) Income', 'House Income', 439000.0, 'pops '],
 [datetime.date(2023, 2, 27), '(-) Expense', 'Savings', 439000.0, 'snp500 '],
 [datetime.date(2023, 2, 27),
  '(+) Income',
  'Reimbursements',
  90000.0,
  'wifi ikbar '],
 [datetime.date(2023, 2, 27),
  '(-) Expense',
  'Engredients Shopping',
  355000.0,
  ' '],
 [datetime.date(2023, 2, 27), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 2, 28),
  '(-) Expense',
  'Food',
  16000.0,
  'latte teras koka '],
 [datetime.date(2023, 2, 28),
  '(-) Expense',
  'Food',
  10000.0,
  'kopi capucino '],
 [datetime.date(2023, 2, 28),
  '(+) Income',
  'House Income',
  1000000.0,
  'pita '],
 [datetime.date(2023, 3, 1), '(-) Expense', 'Social', 109000.0, 'biliar '],
 [datetime.date(2023, 3, 1),
  '(-) Expense',
  'Home Purchases',
  65000.0,
  'sabun '],
 [datetime.date(2023, 3, 1),
  '(+) Income',
  'Reimbursements',
  150000.0,
  'tab taveling '],
 [datetime.date(2023, 3, 1),
  '(-) Expense',
  'Transportation',
  80245.0,
  'kereta bdg ckr '],
 [datetime.date(2023, 3, 1),
  '(-) Expense',
  'Electronics',
  37000.0,
  'win 11 pro '],
 [datetime.date(2023, 3, 1), '(-) Expense', 'Food', 21000.0, 'darso '],
 [datetime.date(2023, 3, 2),
  '(-) Expense',
  'Transportation',
  50000.0,
  'gopay '],
 [datetime.date(2023, 3, 3), '(-) Expense', 'Food', 32200.0, 'kopi kozi '],
 [datetime.date(2023, 3, 3),
  '(-) Expense',
  'Transportation',
  160000.0,
  'kereta ckr bdg '],
 [datetime.date(2023, 3, 4), '(-) Expense', 'Food', 20000.0, 'kopi '],
 [datetime.date(2023, 3, 4),
  '(-) Expense',
  'Transportation',
  15000.0,
  'transport '],
 [datetime.date(2023, 3, 5), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 3, 5),
  '(-) Expense',
  'Medicine',
  39000.0,
  'obat merah dan hansaplast '],
 [datetime.date(2023, 3, 5),
  '(-) Expense',
  'Food',
  72800.0,
  'smara coffee and tofu '],
 [datetime.date(2023, 3, 5), '(-) Expense', 'Beauty', 35000.0, 'senka '],
 [datetime.date(2023, 3, 5), '(-) Expense', 'Food', 49000.0, 'lumintu '],
 [datetime.date(2023, 3, 5), '(-) Expense', 'Food', 54000.0, ' '],
 [datetime.date(2023, 3, 5),
  '(-) Expense',
  'Food',
  96900.0,
  'yomart, sereal susu dsb '],
 [datetime.date(2023, 3, 7), '(-) Expense', 'cash out', 84000.0, 'pita cash '],
 [datetime.date(2023, 3, 7), '(-) Expense', 'Food', 30000.0, ' '],
 [datetime.date(2023, 3, 7), '(-) Expense', 'Admin fee', 9000.0, ' '],
 [datetime.date(2023, 3, 7),
  '(-) Expense',
  'Home Purchases',
  185000.0,
  'biznet '],
 [datetime.date(2023, 3, 7),
  '(-) Expense',
  'Gift',
  52000.0,
  'kopi buat ojan dan cepa '],
 [datetime.date(2023, 3, 7),
  '(-) Expense',
  'Food',
  52500.0,
  'breakfast oxygym '],
 [datetime.date(2023, 3, 8), '(+) Income', 'Gift', 30000.0, 'gift from pops '],
 [datetime.date(2023, 3, 8),
  '(+) Income',
  'Gift',
  1000000.0,
  'buat transport lebaran dari papa '],
 [datetime.date(2023, 3, 8),
  '(-) Expense',
  'Transportation',
  467000.0,
  'kereta bdg yk '],
 [datetime.date(2023, 3, 8), '(-) Expense', 'Food', 20000.0, 'wargot '],
 [datetime.date(2023, 3, 8), '(-) Expense', 'Admin fee', 2000.0, ' '],
 [datetime.date(2023, 3, 8),
  '(-) Expense',
  'Engredients Shopping',
  225000.0,
  'qyam uki '],
 [datetime.date(2023, 3, 8),
  '(-) Expense',
  'Home Purchases',
  31000.0,
  'kunci gerbang '],
 [datetime.date(2023, 3, 9), '(-) Expense', 'Sport', 75000.0, 'gym '],
 [datetime.date(2023, 3, 9),
  '(+) Income',
  'Reimbursements',
  135000.0,
  'ayam nanda '],
 [datetime.date(2023, 3, 9), '(-) Expense', 'cash out', 135000.0, 'cash '],
 [datetime.date(2023, 3, 10), '(-) Expense', 'Food', 20000.0, 'hot capp '],
 [datetime.date(2023, 3, 10),
  '(-) Expense',
  'Gift',
  20000.0,
  'kopi buat pak arie '],
 [datetime.date(2023, 3, 10), '(-) Expense', 'Food', 100500.0, 'steak tsm '],
 [datetime.date(2023, 3, 10), '(-) Expense', 'Admin fee', 4000.0, ' '],
 [datetime.date(2023, 3, 11),
  '(-) Expense',
  'Transportation',
  503501.0,
  'kereta yk bdg '],
 [datetime.date(2023, 3, 11), '(-) Expense', 'Gas', 143000.0, ' '],
 [datetime.date(2023, 3, 11),
  '(-) Expense',
  'Engredients Shopping',
  254264.0,
  'yogya bojong '],
 [datetime.date(2023, 3, 11),
  '(-) Expense',
  'cash out',
  49900.0,
  'turrangga '],
 [datetime.date(2023, 3, 11),
  '(-) Expense',
  'Home Purchases',
  100000.0,
  'listrik '],
 [datetime.date(2023, 3, 11),
  '(+) Income',
  'Reimbursements',
  54000.0,
  'jajan '],
 [datetime.date(2023, 3, 11), '(*) Transfer', '  -  ', 15000.0, ' '],
 [datetime.date(2023, 3, 11), '(-) Expense', 'Food', 20000.0, 'alumni kopi '],
 [datetime.date(2023, 3, 11), '(*) Transfer', '  -  ', 135000.0, ' '],
 [datetime.date(2023, 3, 17), '(-) Expense', 'Gift', 49000.0, 'gopay pita '],
 [datetime.date(2023, 3, 18), '(-) Expense', 'Food', 20000.0, 'esteh '],
 [datetime.date(2023, 3, 20), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 3, 22), '(-) Expense', 'Food', 25000.0, 'kopi '],
 [datetime.date(2023, 3, 22), '(-) Expense', 'Gas', 30000.0, 'bensin scoopy '],
 [datetime.date(2023, 3, 22), '(-) Expense', 'Food', 20000.0, 'warkop '],
 [datetime.date(2023, 3, 23), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 3, 23), '(-) Expense', 'Food', 30000.0, 'lumintu '],
 [datetime.date(2023, 3, 24), '(-) Expense', 'Food', 20000.0, 'warkop '],
 [datetime.date(2023, 3, 26),
  '(+) Income',
  'House Income',
  2500000.0,
  'dari pops '],
 [datetime.date(2023, 3, 26), '(+) Income', 'Gift', 100000.0, 'pita '],
 [datetime.date(2023, 3, 26),
  '(-) Expense',
  'Savings',
  400000.0,
  'travel savings '],
 [datetime.date(2023, 3, 28), '(-) Expense', 'cash out', 100000.0, 'gopay '],
 [datetime.date(2023, 3, 28), '(*) Transfer', '  -  ', 1000000.0, ' '],
 [datetime.date(2023, 3, 28),
  '(-) Expense',
  'Medicine',
  55000.0,
  'shopeepay '],
 [datetime.date(2023, 3, 28),
  '(-) Expense',
  'Engredients Shopping',
  305000.0,
  'yogya '],
 [datetime.date(2023, 3, 29),
  '(-) Expense',
  'Entertainment',
  225000.0,
  'sea of thieves '],
 [datetime.date(2023, 3, 29),
  '(-) Expense',
  'Food',
  30000.0,
  'es kelapa muda '],
 [datetime.date(2023, 3, 29), '(-) Expense', 'Food', 335000.0, 'genki '],
 [datetime.date(2023, 3, 30),
  '(+) Income',
  'House Income',
  1100000.0,
  'uang bulanan pita '],
 [datetime.date(2023, 3, 30),
  '(+) Income',
  'Professional Income',
  1733000.0,
  'momomedia '],
 [datetime.date(2023, 3, 30),
  '(-) Expense',
  'Savings',
  1000000.0,
  'dana darurat '],
 [datetime.date(2023, 3, 30), '(-) Expense', 'Savings', 500000.0, 'snp500 '],
 [datetime.date(2023, 3, 30),
  '(-) Expense',
  'Savings',
  200000.0,
  'travel saving '],
 [datetime.date(2023, 3, 31), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 3, 31),
  '(-) Expense',
  'Electronics',
  35000.0,
  'book reader premium '],
 [datetime.date(2023, 3, 31),
  '(-) Expense',
  'Admin fee',
  31000.0,
  'cumulative administration '],
 [datetime.date(2023, 4, 1), '(-) Expense', 'cash out', 50000.0, 'cash '],
 [datetime.date(2023, 4, 1), '(-) Expense', 'Food', 12500.0, 'hydro coco '],
 [datetime.date(2023, 4, 1),
  '(-) Expense',
  'Bike repairs',
  152500.0,
  'bengkel skupi '],
 [datetime.date(2023, 4, 3), '(-) Expense', 'Sport', 100000.0, 'gym tweak '],
 [datetime.date(2023, 4, 3), '(-) Expense', 'Sport', 100000.0, 'gym tweak '],
 [datetime.date(2023, 4, 4), '(-) Expense', 'Food', 20000.0, 'dana warkop '],
 [datetime.date(2023, 4, 4), '(-) Expense', 'Gas', 30000.0, 'super scoopy '],
 [datetime.date(2023, 4, 4), '(-) Expense', 'Gift', 42000.0, 'buku sheena '],
 [datetime.date(2023, 4, 5), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 4, 5),
  '(-) Expense',
  'Sport',
  74000.0,
  'lifting straps '],
 [datetime.date(2023, 4, 6), '(-) Expense', 'Admin fee', 19000.0, ' '],
 [datetime.date(2023, 4, 6),
  '(-) Expense',
  'Admin fee',
  20000.0,
  'gopay buat parkir '],
 [datetime.date(2023, 4, 6),
  '(-) Expense',
  'Food',
  30000.0,
  'wargot dan tempe '],
 [datetime.date(2023, 4, 7),
  '(-) Expense',
  'Food',
  30000.0,
  'warteg sari rasa '],
 [datetime.date(2023, 4, 7), '(-) Expense', 'cash out', 100000.0, 'cash '],
 [datetime.date(2023, 4, 7), '(-) Expense', 'Food', 95000.0, 'mcd '],
 [datetime.date(2023, 4, 7), '(-) Expense', 'Gas', 30000.0, ' '],
 [datetime.date(2023, 4, 7), '(-) Expense', 'Food', 124000.0, 'ikea jajan '],
 [datetime.date(2023, 4, 7), '(-) Expense', 'Internet', 185000.0, 'wifi '],
 [datetime.date(2023, 4, 7),
  '(+) Income',
  'Reimbursements',
  25000.0,
  'uang protein shake '],
 [datetime.date(2023, 4, 9), '(-) Expense', 'Food', 28000.0, 'wargot '],
 [datetime.date(2023, 4, 10),
  '(-) Expense',
  'Engredients Shopping',
  300000.0,

In [4]:
df = pd.DataFrame([new_record],columns=["TIME", "TYPE", "CATEGORY", "AMOUNT", "NOTES"])

In [5]:
df

         TIME     TYPE CATEGORY AMOUNT NOTES
0  2023-08-28  Expense     Food   9999  test